### ISSUE TITLE
NordVPN updateConfigs.sh not found

### ISSUE THREAD

**Issue by jaspercardol** [guillaumedsde/docker-qbittorrent-openvpn#7]
**Which provider?**
NordVPN

**Where are the configs?**
The configs have remained the same, but everytime I try to use NordVPN I get "updateConfigs.sh" not found on line 12 of configure-openvpn.sh.

It seems the configure-openvpn.sh file is taken from docker-transmission-openvpn, so I tried to run that container with the same env variables. Strangely enough, the issue does not appear there.

**Comment by guillaumedsde** [comment]
Hi, I've stopped supporting this docker image and have moved my efforts to this [alpine based image](https://github.com/guillaumedsde/alpine-qbittorrent-openvpn) instead

**Comment by jaspercardol** [comment]
My apologies, I hadn't noticed. I see I simply created an issue on the wrong project - I am actually using the alpine version.

Will open an issue on that project instead :)
